spring:
  application:
    name: agents-demo
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    openai:
      api-key: ${DEEPSEEK_API_KEY} #openai依赖默认自动配置deepseek
      base-url: ${DEEPSEEK_BASE_URL}
      chat:
        options:
          model: deepseek-chat


# LLM 提供商配置
llm:
  providers:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: # dashscope的起步依赖不需要配置
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: ${DEEPSEEK_BASE_URL}
    # 后面可以再加入新的LLM模型提供商，再在LlmProperties类和配置类里添加对应模型
